ingest_url: "http://127.0.0.1:54322/ingest"
api_key: ""
rooms_allowlist: []
governor_url: "http://127.0.0.1:54323"
recall_top_k: 5
react_success: false
log_level: INFO
cache_ttl_seconds: 300
cache_max_size: 1024
